apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka-node-pool-two
  labels:
    strimzi.io/cluster: kafka-cluster-two
spec:
  replicas: 3
  roles:
    - broker
  storage:
    # https://www.techtarget.com/searchstorage/definition/JBOD
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 200Gi
        deleteClaim: false